version: "3.3"

services:
  manager:
    image: crack-manager:1.0.0
    #build: .
    ports:
      - "8080:8080"
    networks:
      - crack-network

  worker-1:
    image: crack-worker:1.0.0
    ports:
      - "8081"
    networks:
      - crack-network
    depends_on:
      - manager


  rabbitmq:
    image: rabbitmq:3.6-management-alpine

    ports:
      # The standard AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - crack-network

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  crack-network:
    driver: bridge