version: "3.3"

services:
  manager:
    image: crack-manager:1.0.0
    #build: .
    ports:
      - "18080:8080"
    networks:
      - crack-network

  worker-1:
    image: crack-worker:1.0.0
    ports:
      - "8081"
    networks:
      - crack-network
    depends_on:
      - manager

networks:
  crack-network:
    driver: bridge